### ISSUE TITLE
Parameter units

### ISSUE THREAD

**Issue by bstienen** [NLeSC/spot#105]
The units of the parameters, visible via Datasets > [dataset edit screen] > [parameter edit screen], are always empty. Is the implementation correct and does the database contain no value for the units or is there no communication between server and the user's machine about this information?

**Comment by jiskattema** [comment]
The variables' units are not in the database. This type of metadata is stored in the session file.
If units are set on the 'parameter edit screen', they should show up in plots along the axis etc.
