### ISSUE TITLE
Plot absolute values 

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#113]
It would be great if there was an option in under "click to configure" to select absolute values

**Comment by jiskattema** [comment]
Please elaborate; there already are the 'minimum value' and 'maximum value' fields you can set

**Comment by l-hendriks** [comment]
We would like to have the option to plot the abs(x) of all x. So for example there are 3 values: (-1,3,2)

Sometimes it is needed to plot (-1,3,2) and sometimes (1,3,2)

**Comment by jspaaks** [comment]
Perhaps this issue would be resolved by https://github.com/NLeSC/spot/issues/116. You could have ``x`` in the dataset, and then calculate ``abs(x)`` on the fly

**Comment by l-hendriks** [comment]
Yes, you are right. Closing the issue!
