### ISSUE TITLE
In analyze, variables should have a tooltip with a description + categorized in groups

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#114]
When you hover over the different chart options, you get a tooltip with "click to add X". This tooltip should also be visible when you hover over different variables.

It is best I think when the csv has the first row the variable names, second row the variable descriptions and third row the category.

Example naming: https://docs.google.com/spreadsheets/d/1Qgr6BBkxT6Ugb8p8TL1J79GLOtYdMs2-Po2ujTMggI4/edit?usp=sharing

See columns F (name), D (description) and G (category).

**Comment by jiskattema** [comment]
The tooltip is set using the Facet's description field.

By default: when importing data, this is set to a sample of occurring values. It can be a bit more descriptive. Parsing the description etc. like you describe from the CSV file will be too fragile (loading arbitrary CSV files with or without multiline headers is not supported by our CSV reader, so we would have to hack around it..)

For your own (pre-defined) datasets, you can generate or hand-edit the session file.

**Comment by jiskattema** [comment]
Updated framework and server to add facet type to default description.
