### ISSUE TITLE
Bookmarkable session

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/spot#118]
Make session bookmarkable/shareable with url like `http://nlesc.github.io/spot#session=http://somewhere/spot-session.json`. This url can be shared so that the same session is loaded.

By uploading a session json file somewhere on the Internet, 

Spot could generate such an url in the Share menu.

**Comment by fdiblen** [comment]
Implemented in 6c2c945fda8a798a25076785b85b6d0c7b39eb63
