### ISSUE TITLE
Can't adjust Upload CSV file settings in Firefox 

### ISSUE THREAD

**Issue by arnikz** [NLeSC/spot#121]
Hi, I can't change the settings to upload e.g. a TSV file; the settings window does not show up when clicking on the 'blue cog wheel'. Tested on Firefox 56.0 on OS X (10.11.2). Inspector gives me the following error:

```
TypeError: dialog.showModal is not a function[Learn More] datasets.js:318
	showCSVSettings datasets.js:318
	cb index.js:100
	[116]</exports.bind/<
```

**Comment by fdiblen** [comment]
fixed in dev.
