### ISSUE TITLE
CSV import radio button status and settings not always stored

### ISSUE THREAD

**Issue by franktakes** [NLeSC/spot#144]
When adjusting the CSV import settings, it does not always store the changes.
Also, when clicking "No quoting", nothing happens (the radio button doesn't work).

**Comment by fdiblen** [comment]
Thanks for reporting the issue.
Could you give more information about your system?
Web browser, operating system ( Linux distro if it is a Linux system).

**Comment by franktakes** [comment]
Both Ubuntu 16.04 and Windows 10 (so likely not OS-related), all in Chrome latest

**Comment by franktakes** [comment]
Tried just now, and the storing of settings seems to work now; no more radio buttons not functioning.
The "No quoting" radio button still does not work (nothing happens when you click it).
On the same Ubuntu 16.04 machine.

**Comment by fdiblen** [comment]
@franktakes: I believe you are using the Github demo page. Actually, there are no changes at all in the demo page.
The changes are in "dev" branch. You need to checkout the dev branch and build SPOT. Please follow the instructions and let us know if we can help you with this.
We try to be careful not to break anything when we add new features. When the master branch gets updated, the demo page will also be updated.

**Comment by franktakes** [comment]
Yes, I am using the demo page, mainly to test and play around with Spot.
I am sure that the error I mentioned with settings not being stored was persistent at the moment that I reported it, and there were some friendly eScience engineers standing behind me when it happened who also didn't know why it happened ;)
But alright, it seems to work now and I am playing around with the dataset, so that's good :+1:

**Comment by fdiblen** [comment]
Great! Please keep creating Github issues. This helps us a lot to improve the code.
Closing the issue. Please reopen if it is needed.
