### ISSUE TITLE
CSV import not working

### ISSUE THREAD

**Issue by franktakes** [NLeSC/spot#146]
I imported several tab-separated files with headers that parse properly in for example tools like Pandas, Python CSV reader and Gephi 0.9.2 (which is rather strict). 
However, when I import them into spot, they do appear as datasets (although it also once just randomly didn't show up), but clicking the switch to "active" them does nothing, hangs, and upon refreshing the page seems as if it was never clicked.

**Comment by fdiblen** [comment]
What is your web browser, and OS?
Could you give us a small CSV file to reproduce your problem?

**Comment by franktakes** [comment]
To be honest I cannot get it to load any CSV file, regardless of the format. Perhaps you can give me a CSV file that you know works?

**Comment by fdiblen** [comment]
I have just tried it with a simple CSV file and there is no problem.
You can use the attached CSV file. The file was generated using the code snipped in our tutorial.
https://nlesc.github.io/spot-tutorial/tutorial
[simple_data.txt](https://github.com/NLeSC/spot/files/1720662/simple_data.txt)

**Comment by franktakes** [comment]
I can confirm that the file you linked, works.
Handy that there is some extra explanation on the import step :)

As reported in #144, it seems to store the clicked import settings now. 
That was perhaps the problem here as well, as now I seem to be able to import my own dataset, which is tab-separated (and the tab as delimiter setting was not stored).

Quick comment: the tutorial seems to suggest to separate by 2 characters; comma and space. The CSV-format traditionally has 1 character as a delimiter. The advantage would be that there is no need to use escape characters on cells which contains a space.

**Comment by fdiblen** [comment]
Updated the snippet in the tutorial.
