### ISSUE TITLE
Time series

### ISSUE THREAD

**Issue by nmanuben** [NLeSC/spot#149]
Hello,

We've been shown this cool and robust application. We'd like however to see an example working with time series (each value with an associated data). 

Thank you,
Nicolau

**Comment by jiskattema** [comment]
Hi Nicolau,

thanks for you interest! There is nothing special or different for time series; we treat every dataseries the same. Plotting fi. (x,y) or (x,t) does not differ:
1) upload your data;
2) check the facets; auto detection of the data types is not perfect yet. so check that your time fields are recognized as a datetime. This will help parsing, binning, and plotting time.
3) create a plot, and drag the facets (variables) to the axis you want.
