### ISSUE TITLE
invisible share menu

### ISSUE THREAD

**Issue by bakhshir** [NLeSC/spot#151]
The left menu section "share" is not visible but is still there (see attached screenshot). I'm using Firefox Quantum.

![Screenshot from 2018-02-16](https://user-images.githubusercontent.com/16703268/36307314-f16dd08a-131b-11e8-8030-eee93b34efa8.png)

**Comment by fdiblen** [comment]
fixed by 9c464fefbeb0b7328f4dfd2fea1dc42b35039a8a
