### ISSUE TITLE
Icon for zooming on a subset is unclear

### ISSUE THREAD

**Issue by evertrol** [NLeSC/spot#170]
The icon for zooming in on a selection in a graph is unclear.

The standard `+` is probably not the right choice, since that implies the graph will be zoomed (probably at the center); which is not an option here.

Perhaps something similar to one of the following (provided this is not too busy at the smaller scale):
- https://www.iconfinder.com/icons/1132916/find_fit_page_search_selection_window_zoom_icon
- https://www.onlinewebfonts.com/icon/468247
- https://www.iconfinder.com/icons/354927/arrows_enlarge_expand_fullscreen_icon
- https://www.iconfinder.com/icons/444633/in_magnifier_marquee_selection_zoom_icon

**Comment by fdiblen** [comment]
fixed in dev.
