### ISSUE TITLE
Titanic demo shows an empty Fare graph

### ISSUE THREAD

**Issue by evertrol** [NLeSC/spot#176]
If I go directly to the demo (new window), I get the seven preconfigured graphs with the Titanic dataset. But the "count by Fare" graph is empty!

If I configure the graph: remove "Fare" from the X axis, then add "Fare" back again, I get the intended graph. So it works, but there is something amiss with the initial setup.

Something similar happens when I select a point in the "count by Fare" graph: the graph zooms in (even before I select the "zoom to selection" button though!), then clicking on "undo" shows me an empty graph again.

It would appear the scaling of the y-axis is problematic, often defaulting to -1.0 to 1.0, thus not showing the full dataset.
Trying this with another dataset (e.g. a Fermi dataset) doesn't show this issue.

**Comment by fdiblen** [comment]
fixed in dev
