### ISSUE TITLE
"Help" in the menu isn't really a help

### ISSUE THREAD

**Issue by evertrol** [NLeSC/spot#180]
The "Help" option in the side menu results in a short walkthrough of the various items on the current page. While this is fine(*), I expected a page (or pages) similar to the tutorial, sectioned by topics and with a more in-depth description of things. That is, standard-style documentation.

The current walkthrough option could perhaps be changed by using an icon (simply a "?" icon) on the top-right of the relevant page (next to other icons, if available): selecting this would allow a user to highlight a section or tool on the current page, and show an informative pop-up page (similar to a single item in the walk-through).

(*) The walkthrough doesn't actually provide much extra beyond the tooltips and what is already on the page; perhaps highlighting an overlooked option. 
In addition, the area of the pop-up with the exit, back and next buttons *moves along* with the highlights, making it frustrating to use, as I have to move my mouse each time to click "next". That would be another issue, but since I'm not in favour of the current walkthrough style (see second paragraph), I'll leave that to someone else.

**Comment by fdiblen** [comment]
fixed in dev.
