### ISSUE TITLE
Session share link of file.io only works once

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#192]
The session json is deleted from file.io after is has been downloaded once. So if person A opens the session, then person B cannot open it anymore.

**Comment by fdiblen** [comment]
The file.io was used to demonstrate the idea. Developers of course can use any other file sharing platform. 
As you mentioned, file.io only allows files to be downloaded once so this is not about SPOT.

If you know any other file free and secure sharing platform, with REST API, we can switch to that.

**Comment by fdiblen** [comment]
fixed in dev. file sharing now uses Zenodo.
