### ISSUE TITLE
link to online documentation is broken

### ISSUE THREAD

**Issue by robertoostenveld** [NLeSC/spot#199]
The top-level README.md in the repository states "The spot documentation can be found here" and links to http://nlesc.github.io/spot/doc/spot/0.1.0/index.html, but that link is broken.

**Comment by robertoostenveld** [comment]
This is actually specifically for the https://github.com/NLeSC/spot/tree/0.1.0 tagged version, which is the one published on zenodo, where I arrived after following the DOI that is linked on https://www.research-software.nl/software/spot.

The master version does  not have the broken link.

**Comment by robertoostenveld** [comment]
The master README.md contains "SPOT api documentation can be found here" which links to https://spot-demo.netlify.com/docs/api. That URL is also broken.

**Comment by fdiblen** [comment]
@robertoostenveld thank you for reporting. I have updated the links.
