### ISSUE TITLE
Testing SPOT for visualization and analysis of ODEX4all triples

### ISSUE THREAD

**Issue by asijbers** [NLeSC/spot#43]
I am trying to visualize and analyze my data (ODEX4all project) using SPOT. Here I wrote down some of the issues I came across while working with SPOT:
- Is it possible to remove uploaded data files?
- In case of 3 loaded data files, the button to upload data has moved or is gone?
- When changing the column selection; figures are not reset. It is hard to drag and drop the column number to remove the previously selected column and add a new column number.
- When label(s) is (are) removed from a graph, is it possible to get it (them) back without having to start all over again?
- Generation of network from 3 columns does not seem to work
I would be happy to learn more about the possibilities of SPOT. If you like we could meet at NLeSC to discuss the use of SPOT within the ODEX4all project (anneke.sijbers@nizo.com).

**Comment by jiskattema** [comment]
Thanks for the feedback, trying out our tool.
Some quick answers your direct questions:

* The multiple datasets features are still under heavy development.  Adding and removing datasets will be added in the coming version.
* user interface for adding data will be updated then, too.
* You can delete labels from the chart by using on the '-' button on the 'configure partition' page. To reset all labels, use the 'SCAN DATASET' button on the top.
* 3 column networks, ie. subject to object, with linecolor set by predicate works in current (development) version. Can you add a small datafile that is not working?

You are welcome to come visit us and discuss things. Please arrange details via the escience engineer on your project; or we can pick this up after the christmas break, in 2017.

**Comment by fdiblen** [comment]
Could you please try the latest version of SPOT? Please let us know if we can fix anything for you.

**Comment by jiskattema** [comment]
We have changed the interface a lot since your comment; please have a look.
You can open new issues where necessary.
