### ISSUE TITLE
Button to select all data

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/spot#45]
When I have zoomed in on a particular slice of the data, it seems like there is no way to go back to all the data again. I would like to have one reset-selection button to select all data again.

**Comment by jiskattema** [comment]
the button next to the 'zoom-in' button, zooms out again. This is per plot.
Removing a plot will also remove any filters associated with the plot, effectively zooming out.

**Comment by jiskattema** [comment]
Selecting data needs more intuitive interface. See also issue #50
