### ISSUE TITLE
Question: how to recreate a plot from idarksurvey with spot?

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#58]
Not sure if this is the right place as it technically is not an error. I tried using the green points plot on idarksurvey.com (data_pf.csv that I sent a while back) to recreate the default scatter plot of idarksurvey.com. This is a scatter plot of the columns `nmass` vs `m1`.

I upload the csv file and select a bubbleplot chart. When I click on the view mode instead of the edit mode I get one huge bubble with a few bubbles on it. I can click on the zoom or fullscreen button but nothing happens. The plot is not very insightful compared to the demo one. See the two screenshots:

<img width="1370" alt="screen shot 2017-02-25 at 11 02 50 am" src="https://cloud.githubusercontent.com/assets/4309740/23330253/0b98d9ea-fb4a-11e6-8f11-4427ad3667ec.png">
<img width="351" alt="screen shot 2017-02-25 at 11 03 21 am" src="https://cloud.githubusercontent.com/assets/4309740/23330254/0b996ad6-fb4a-11e6-84bc-fab704279963.png">

My question is: how can I create the idarksurvey plot with SPOT? I understand that clustering is needed, but the amount of clusters should be user definable (maybe even turned off, so n_clusters = n_points, with a warning if there are too many clusters in that case).

**Comment by l-hendriks** [comment]
note that I didn't tweak anything, these are just all defaults

**Comment by fdiblen** [comment]
Fixed by 8003b516bd7dcc4e7b287ce45ae8b6365dba9437
