### ISSUE TITLE
Default range gives "Input is not a number!"

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#65]
<img width="581" alt="screen shot 2017-03-10 at 3 18 46 pm" src="https://cloud.githubusercontent.com/assets/4309740/23798438/f6e0ce08-05a4-11e7-9384-77f4d4e3f09d.png">

Create plot
Add variable
Click on the variable to edit the range
If the range is very small, it gives the error

**Comment by fdiblen** [comment]
@l-hendriks  Can you please provide a datasets to reproduce the issue?

**Comment by l-hendriks** [comment]
This example is from the `sv` column of the `pf_scan.csv` dataset.
