### ISSUE TITLE
Cannot select specific region

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#67]
The rectangle selector does not allow to select this region completely

<img width="122" alt="screen shot 2017-03-10 at 3 40 02 pm" src="https://cloud.githubusercontent.com/assets/4309740/23799168/dae055ae-05a7-11e7-8443-435e40211646.png">

The plot is from pf_scan.csv m1 vs oh2 (mu is color code)

**Comment by jiskattema** [comment]
You can manually filter a range when configuring a partition, ie click on the button labelled 'm1' or
 'oh2' in your case.
For now, you need to click on a point to select it, and clicking on empty space unselects everything.
To do proper rectangle selection we need an alternative way to unselect.

**Comment by jiskattema** [comment]
Selecting / zooming (drill-down) / unselecting has been reworked.
Please open a new issue if selecting is still impossible
