### ISSUE TITLE
Loading indicator for large datasets in Analyze

### ISSUE THREAD

**Issue by bstienen** [NLeSC/spot#70]
Analysing a large dataset takes possibly a long time. It would be nice that after changing the selected facets for a specific plot a loading indicator would appear, to show that something is happening at all.

**Comment by jiskattema** [comment]
There now is a progress bar at the bottom of the page during file upload.
The next step, processing does give a progress indication yet.

**Comment by jiskattema** [comment]
Parsing large datasets (166MB, in your case) is still slow for client side datasets.
For these cases, the postgreSQL backend is recommended.
Please open a new issues for overall performance when using client side datasets.
