### ISSUE TITLE
Selecting or deselecting facets is slow for large datasets

### ISSUE THREAD

**Issue by bstienen** [NLeSC/spot#71]
When changing the selection of facets on the Dataset page, the website becomes unresponsive for a couple of seconds for large datasets. I can imagine this is because in the background some memory is altered of shifted around, but initially I did not know this was the case and I thought the webpage was not working. It is forgivable this operation possibly takes some time, but I would like it if the website would clearly indicate it was doing something.

**Comment by bstienen** [comment]
The used 'large dataset' can be downloaded from http://hef.ru.nl/~bstienen (PMSSM dataset)

**Comment by jiskattema** [comment]
There is now a spinner for activating a dataset, and a progress bar for uploading a dataset. See #70 
If there are any other parts of the site that need some sort of progress/feedback discuss at that issue.
