### ISSUE TITLE
NPM install requires more dependencies

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#86]
When building on a completely empty ubuntu install, I have to run these commands as well to get the dependencies working:

```
# apt-get install build-essential
# apt-get install python
# apt-get install libpq-dev
```

Otherwise node-gyp does not compile. Maybe add to readme?

**Comment by fdiblen** [comment]
Hi,
Thanks for reporting. I think you are referring to Node.js installation. I have just followed the [official installation instructions](https://nodejs.org/en/download/package-manager/) on a fresh system and it works out of the box.

Can you please give me more details?

**Comment by l-hendriks** [comment]
Hi Faruk,

I actually used the same method, I guess it should be enough to use install the build tools and was quite puzzled I needed python for some node dependency (sometimes this is preinstalled).

Anyway, maybe a mention that native addons are required and that you should install also the optional part is enough.

**Comment by fdiblen** [comment]
Added info to README. Closing the issue.
