### ISSUE TITLE
Server listens to localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot#87]
When I have a webserver on ip adress `w.x.y.z` and do npm start, I can ssh into the server and do `wget localhost:9966` to get index..html, but when I go to `w.x.y.z:9966` it does not work because the server doesn't listen to that ip address.

In node, you can listen to `0.0.0.0` so it works on any ip address and localhost as well.

Example: `http://54.93.46.86:9966/` (Farum has root access to this server)

**Comment by fdiblen** [comment]
You can change this in **package.json**:

"start": "npm run fonts && npm run templates && npm run css-watch & budo -v -P --host **localhost** --live --dir dist --css app.css client/app.js -- -v"

For a production server, using a real webserver(apache for example) will be a better option.
