### ISSUE TITLE
Facet selection in plot impossible due to horizontal fold

### ISSUE THREAD

**Issue by bstienen** [NLeSC/spot#90]
When selecting a new plot, facets have to be dropped in it to fully configure the plot. In the current spot version, there are nice new boxes that specify the role the dropped facet would have (which I like by the way!). However, these boxes are all put next to each other and the entirety of these boxes is centered with not possibility to horizontally scroll through them. The problem now arises when these boxes are wider then the box of the plot one wants to make (see image):

<img width="1116" alt="screen shot 2017-05-17 at 11 42 05" src="https://cloud.githubusercontent.com/assets/25798453/26148371/b4e0b108-3af6-11e7-87b9-e5ccd0fe74ad.png">

There is now no possibility to drop facets in the x-axis box for example.

**Comment by fdiblen** [comment]
Can you please give me some information about your system?

This is what I have with Chrome Version 58.0 (64-bit) on Linux.

![spot_facet](https://cloud.githubusercontent.com/assets/144492/26149537/f1ba21dc-3afa-11e7-88bb-98ed023d49d0.png)

**Comment by bstienen** [comment]
I am using:

macOS Sierra (version 10.12.5) 64-bit
Safari version 10.1.1 (12603.2.4)
     no plugins installed

**Comment by fdiblen** [comment]
Can you please test it with Chrome browser? 
If it works, I will create an issue for testing the interface for Safari.

**Comment by bstienen** [comment]
That does seem to solve the problem with the horizontal scrolling, but now when I for example want to create a bubbleplot some boxes are vertically "below the fold", with no clear indication there are still boxes out of view. By resizing the bubbleplot box you can overcome this problem, but it is still not exactly as you would typically want I think?

**Comment by fdiblen** [comment]
Seems to be working on version 0.1.0. Closing the issue. Please re-open the issue if it is needed.
